### ISSUE TITLE
Stappen beeldherkenning

### ISSUE THREAD

**Issue by damianooldoni** [inbo/mica-beeldherkenning#3]
Vanuit https://github.com/inbo/mica-beeldherkenning/issues/1#issuecomment-669802721 maak ik een lijst met de verschillende stappen voor de beeldherkenning:

- [x] Preprocessing - resize_images.py
- [x] Preprocessing - run preprocessing.py
- [ ] Training - run resnet50_bottleneck_features.py (map network)
- [ ] Training- run resnet50_hierarchical_bottleneck (map network)
- [ ] Training - run resnet50_hierarchical_finetune (top weights nog te bepalen, ik zal dit aan Laura vragen)
- [ ] Evaluate: hierachical_output_processing_training.py

**Comment by SanderDevisscher** [comment]
boxes_preprocessing_single.csv & boxes_preprocessing_single.csv blijken niet de juiste velden te bevatten = >terug naar preprocessing :-(

**Comment by SanderDevisscher** [comment]
M.i.z. behandeld de originele versie van het preprocessing script enkel sequenties met meer dan 10 foto's maar hoe de test data is opgebouwd heeft iedere sequentie slechts 1 foto waardoor het script feitelijk niks doet. Ik dacht dit met  deze commit 3502ca66ba9a12913476ea886cd052097f0b080a op te lossen maar hierdoor wordt de foto met zichzelf vergeleken met "NULL" - verschil tot gevolg, zie onderstaande code:

https://github.com/inbo/mica-beeldherkenning/blob/3502ca66ba9a12913476ea886cd052097f0b080a/src/preprocessing/preprocessing.py#L296-L322

![image](https://user-images.githubusercontent.com/16779320/89810730-cef6f300-db3d-11ea-8388-8e6b25be839e.png)

Ik heb een vermoeden dat er ergens in de onderstaande stukken code iets foutloopt  waardoor de sequenties opgebroken worden.

https://github.com/inbo/mica-beeldherkenning/blob/3502ca66ba9a12913476ea886cd052097f0b080a/src/preprocessing/preprocessing.py#L97-L103

of 

https://github.com/inbo/mica-beeldherkenning/blob/3502ca66ba9a12913476ea886cd052097f0b080a/src/preprocessing/preprocessing.py#L216-L225

**Comment by EmmaCartuyvels1** [comment]
Get original data agouti:
https://drive.google.com/drive/folders/1elXENZbBT05BwnrMQyTI2mCElCRVnMS9?usp=sharing

**Comment by SanderDevisscher** [comment]
Het preprocessing script geeft nu outputs met inhoud => checken/zorgen of/dat de training met deze inhoud verder kan

**Comment by SanderDevisscher** [comment]
@EmmaCartuyvels1 
Ik heb atm wel een bottleneck mbt tot de training scripts, hiervoor is het package tensorflow nodig en daarvoor heb ik atm niet de juiste versie van python op mijn laptop staan (zie https://stackoverflow.com/questions/48720833/could-not-find-a-version-that-satisfies-the-requirement-tensorflow). Ik heb reeds een helpdesk call geplaatst.

**Comment by SanderDevisscher** [comment]
@EmmaCartuyvels1 ik denk toch dat die extra reken capaciteit geen overbodige luxe gaat zijn. 

ik krijg de hele tijd van deze meldingen gevolgd door een freezing van mijn pc 
```
2020-08-12 15:51:24.664445: W tensorflow/core/framework/allocator.cc:107] Allocation of 160963200 exceeds 10% of system memory.
2020-08-12 15:51:25.674751: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
2020-08-12 15:51:34.062726: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
2020-08-12 15:51:34.062725: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
2020-08-12 15:51:38.612849: W tensorflow/core/framework/allocator.cc:107] Allocation of 848742400 exceeds 10% of system memory.
```

p.s. ik heb 8gig ddr3 ram in mijn bakske steken + 10gig GPU memory

**Comment by SanderDevisscher** [comment]
Momenteel loopt er nog iets mis in de laatste regel van het script resnet50_bottleneck_features.py. zie onder:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/blauw/Documents/GitHub/mica-beeldherkenning/src/network/resnet50_bottleneck_features.py", line 93, in <module>
    train, validation, test, bottleneck_features_train, bottleneck_features_validation, bottleneck_features_test = split_train_val_test_bottleneck(data, bottleneck_features, 0.5, 0.25, bottleneck_features_output_path)
  File "C:\Users\blauw\Documents\GitHub\mica-beeldherkenning\src\network\functions_network.py", line 284, in split_train_val_test_bottleneck
    seq_train, seq_testing = train_test_split(bottleneck_sequences.sequence, test_size=(1-train_size), stratify = bottleneck_sequences.ann_animal)
  File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 2152, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
  File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 1341, in split
    for train, test in self._iter_indices(X, y, groups):
  File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 1668, in _iter_indices
    raise ValueError("The least populated class in y has only 1"
ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
```
Hiervoor zal moeten gekeken worden in de functies onder **_split_train_val_test_bottleneck_**.

**Comment by EmmaCartuyvels1** [comment]
> @EmmaCartuyvels1 ik denk toch dat die extra reken capaciteit geen overbodige luxe gaat zijn.
> 
> ik krijg de hele tijd van deze meldingen gevolgd door een freezing van mijn pc
> 
> ```
> 2020-08-12 15:51:24.664445: W tensorflow/core/framework/allocator.cc:107] Allocation of 160963200 exceeds 10% of system memory.
> 2020-08-12 15:51:25.674751: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
> 2020-08-12 15:51:34.062726: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
> 2020-08-12 15:51:34.062725: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
> 2020-08-12 15:51:38.612849: W tensorflow/core/framework/allocator.cc:107] Allocation of 848742400 exceeds 10% of system memory.
> ```
> 
> p.s. ik heb 8gig ddr3 ram in mijn bakske steken + 10gig GPU memory

Ik zal er meteen eens voor mailen :)

**Comment by SanderDevisscher** [comment]
> > @EmmaCartuyvels1 ik denk toch dat die extra reken capaciteit geen overbodige luxe gaat zijn.
> > ik krijg de hele tijd van deze meldingen gevolgd door een freezing van mijn pc
> > ```
> > 2020-08-12 15:51:24.664445: W tensorflow/core/framework/allocator.cc:107] Allocation of 160963200 exceeds 10% of system memory.
> > 2020-08-12 15:51:25.674751: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
> > 2020-08-12 15:51:34.062726: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
> > 2020-08-12 15:51:34.062725: W tensorflow/core/framework/allocator.cc:107] Allocation of 829440000 exceeds 10% of system memory.
> > 2020-08-12 15:51:38.612849: W tensorflow/core/framework/allocator.cc:107] Allocation of 848742400 exceeds 10% of system memory.
> > ```
> > 
> > 
> > p.s. ik heb 8gig ddr3 ram in mijn bakske steken + 10gig GPU memory
> 
> Ik zal er meteen eens voor mailen :)

oja vergeten te vermelden men pc was +- 10min onbruikbaar en ik test atm maar met 2 sequenties :-/

**Comment by SanderDevisscher** [comment]
> Momenteel loopt er nog iets mis in de laatste regel van het script resnet50_bottleneck_features.py. zie onder:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "C:/Users/blauw/Documents/GitHub/mica-beeldherkenning/src/network/resnet50_bottleneck_features.py", line 93, in <module>
>     train, validation, test, bottleneck_features_train, bottleneck_features_validation, bottleneck_features_test = split_train_val_test_bottleneck(data, bottleneck_features, 0.5, 0.25, bottleneck_features_output_path)
>   File "C:\Users\blauw\Documents\GitHub\mica-beeldherkenning\src\network\functions_network.py", line 284, in split_train_val_test_bottleneck
>     seq_train, seq_testing = train_test_split(bottleneck_sequences.sequence, test_size=(1-train_size), stratify = bottleneck_sequences.ann_animal)
>   File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 2152, in train_test_split
>     train, test = next(cv.split(X=arrays[0], y=stratify))
>   File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 1341, in split
>     for train, test in self._iter_indices(X, y, groups):
>   File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 1668, in _iter_indices
>     raise ValueError("The least populated class in y has only 1"
> ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
> ```
> 
> Hiervoor zal moeten gekeken worden in de functies onder **_split_train_val_test_bottleneck_**.

Ik vermoed dat dit een gevolg is omdat ik nu slechts 2 volledige sequenties gebruik en er minimaal 4 nodig heb. 
=> testing

**Comment by EmmaCartuyvels1** [comment]
> > Momenteel loopt er nog iets mis in de laatste regel van het script resnet50_bottleneck_features.py. zie onder:
> > ```
> > Traceback (most recent call last):
> >   File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1438, in _exec
> >     pydev_imports.execfile(file, globals, locals)  # execute the script
> >   File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
> >     exec(compile(contents+"\n", file, 'exec'), glob, loc)
> >   File "C:/Users/blauw/Documents/GitHub/mica-beeldherkenning/src/network/resnet50_bottleneck_features.py", line 93, in <module>
> >     train, validation, test, bottleneck_features_train, bottleneck_features_validation, bottleneck_features_test = split_train_val_test_bottleneck(data, bottleneck_features, 0.5, 0.25, bottleneck_features_output_path)
> >   File "C:\Users\blauw\Documents\GitHub\mica-beeldherkenning\src\network\functions_network.py", line 284, in split_train_val_test_bottleneck
> >     seq_train, seq_testing = train_test_split(bottleneck_sequences.sequence, test_size=(1-train_size), stratify = bottleneck_sequences.ann_animal)
> >   File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 2152, in train_test_split
> >     train, test = next(cv.split(X=arrays[0], y=stratify))
> >   File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 1341, in split
> >     for train, test in self._iter_indices(X, y, groups):
> >   File "C:\Users\blauw\anaconda3\lib\site-packages\sklearn\model_selection\_split.py", line 1668, in _iter_indices
> >     raise ValueError("The least populated class in y has only 1"
> > ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.
> > ```
> > 
> > 
> > Hiervoor zal moeten gekeken worden in de functies onder **_split_train_val_test_bottleneck_**.
> 
> Ik vermoed dat dit een gevolg is omdat ik nu slechts 2 volledige sequenties gebruik en er minimaal 4 nodig heb.
> => testing

Kan misschien ook te maken hebben dat je van elk label (eg muskusrat, leeg, eend, ...) er minstens 2 nodig hebt?

**Comment by SanderDevisscher** [comment]
to enable GPU - processing install CUDA 10.1 found [here](https://developer.nvidia.com/cuda-10.1-download-archive-base?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal) 

if other .dll's are missing check info at https://www.tensorflow.org/install/gpu

**Comment by SanderDevisscher** [comment]
vervolgens in annaconda prompt doe:
```
 conda create -n tensorflow
 activate tensorflow
 pip install --ignore-installed --upgrade tensorflow-gpu
```

en in pycharm

![image](https://user-images.githubusercontent.com/16779320/91170891-d8559300-e6d9-11ea-8528-7ff1eee0923c.png)

**Comment by SanderDevisscher** [comment]
@EmmaCartuyvels1 het lukt me niet om  resnet50_bottleneck_features.py draaiende te krijgen. Daarom heb ik het script even doorgespeeld aan Jo Loos, in de hoop dat het hem wel lukt.

**Comment by EmmaCartuyvels1** [comment]
> @EmmaCartuyvels1 het lukt me niet om resnet50_bottleneck_features.py draaiende te krijgen. Daarom heb ik het script even doorgespeeld aan Jo Loos, in de hoop dat het hem wel lukt.

Okido, laat maar weten wat of hij ermee weg kan
